In [1]:
import numpy as np

In [72]:
class Matrix:
    def __init__(self, size):
        ## Array is defined by array[row][column]
        columns = size
        rows = size
        self.array = [[0 for _ in range(columns)] for _ in range(rows)]
        self.size = size
    
    def set_matrix(self, new_matrix):
        self.array = new_matrix
    
    def get_matrix(self):
        return self.array
    def set_value(self, row, column, value):
        self.array[row][column] = value
    
    def multiply(self, another_matrix, operator):
        other_array = another_matrix.get_matrix()
        assert len(other_array) == len(other_array[0]) == self.size 
        result = [[0 for _ in range(self.size)] for _ in range(self.size)]
        for thisRow in range(len(self.array)):
            for thisColumn in range(len(self.array[0])):
                result[thisRow][thisColumn] = self.__helper_mult(thisRow, thisColumn, other_array, operator)
        return result
    
    def __helper_mult(self, row, column, other_array, operator):
        total = operator.OP1_ID
        for c in range(len(other_array)):
            other_value = other_array[c][column]
            this_value = self.array[row][c]
            total = operator.op1(total,operator.op2(this_value, other_value))
        return total
    def copy(self):
        new_array = [row[:] for row in self.array]
        result = Matrix(size)
        result.set_matrix(new_array)
        return result
    
    def printSelf(self):
        print(np.matrix(self.array))
    
class AddMult:
    OP1_ID = 0
    OP2_ID = 1
    @staticmethod
    def op1(a, b):
        return a + b
    @staticmethod
    def op2(a, b):
        return a * b
    
def printMatrix(array):
    print(np.matrix(array))

In [73]:
m = Matrix(3)
m.set_value(0,0,1)
m.set_value(1,1,1)
m.set_value(2,2,1)
m.set_value(2,1,2)
m.printSelf()
print()
printMatrix(m.multiply(m, AddMult()))


[[1 0 0]
 [0 1 0]
 [0 2 1]]

[[1 0 0]
 [0 1 0]
 [0 4 1]]
